// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5M1iqK8fOBp9RIeQJ-SN1LDN-JZDpR9Q',
    appId: '1:56961598499:web:9a3a21d640ee4308a99d96',
    messagingSenderId: '56961598499',
    projectId: 'justbus-519da',
    authDomain: 'justbus-519da.firebaseapp.com',
    storageBucket: 'justbus-519da.firebasestorage.app',
    measurementId: 'G-8XW936TRJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC6VKSbihTfg99c3vbY7ZVS8-oHX927Ms',
    appId: '1:56961598499:android:ae40ddf4fded9bb5a99d96',
    messagingSenderId: '56961598499',
    projectId: 'justbus-519da',
    storageBucket: 'justbus-519da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl7uZRTfL4DfXFWvfEI-uR5TnS6Fom9Ks',
    appId: '1:56961598499:ios:bc9cfc4879d24d5ea99d96',
    messagingSenderId: '56961598499',
    projectId: 'justbus-519da',
    storageBucket: 'justbus-519da.firebasestorage.app',
    iosBundleId: 'com.example.justbusV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl7uZRTfL4DfXFWvfEI-uR5TnS6Fom9Ks',
    appId: '1:56961598499:ios:bc9cfc4879d24d5ea99d96',
    messagingSenderId: '56961598499',
    projectId: 'justbus-519da',
    storageBucket: 'justbus-519da.firebasestorage.app',
    iosBundleId: 'com.example.justbusV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5M1iqK8fOBp9RIeQJ-SN1LDN-JZDpR9Q',
    appId: '1:56961598499:web:f07fb7017a5fc1bfa99d96',
    messagingSenderId: '56961598499',
    projectId: 'justbus-519da',
    authDomain: 'justbus-519da.firebaseapp.com',
    storageBucket: 'justbus-519da.firebasestorage.app',
    measurementId: 'G-PLBH986MS5',
  );
}
