// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBQRcmldCMxjtS4EsOIUTx9PgYJKVX268',
    appId: '1:361183183718:web:8e9ec29c873adc04c93ea7',
    messagingSenderId: '361183183718',
    projectId: 'just-bus-f2b31',
    authDomain: 'just-bus-f2b31.firebaseapp.com',
    storageBucket: 'just-bus-f2b31.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBzOoJOXp9zCySPnXGeAJbLDRNrAM_-MY',
    appId: '1:361183183718:android:2df105cbc1b2b0a8c93ea7',
    messagingSenderId: '361183183718',
    projectId: 'just-bus-f2b31',
    storageBucket: 'just-bus-f2b31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxHQ7ryQAZhHbx5fQlXMzzCx5GhGXm4Jw',
    appId: '1:361183183718:ios:49eaf7e0ed647cdfc93ea7',
    messagingSenderId: '361183183718',
    projectId: 'just-bus-f2b31',
    storageBucket: 'just-bus-f2b31.firebasestorage.app',
    iosBundleId: 'com.example.justbusV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxHQ7ryQAZhHbx5fQlXMzzCx5GhGXm4Jw',
    appId: '1:361183183718:ios:49eaf7e0ed647cdfc93ea7',
    messagingSenderId: '361183183718',
    projectId: 'just-bus-f2b31',
    storageBucket: 'just-bus-f2b31.firebasestorage.app',
    iosBundleId: 'com.example.justbusV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBQRcmldCMxjtS4EsOIUTx9PgYJKVX268',
    appId: '1:361183183718:web:264b65b2089ccebdc93ea7',
    messagingSenderId: '361183183718',
    projectId: 'just-bus-f2b31',
    authDomain: 'just-bus-f2b31.firebaseapp.com',
    storageBucket: 'just-bus-f2b31.firebasestorage.app',
  );
}
